{
 "title": "My Application",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "memory_limit", "query": "536870912" }
  ]
 },
 "panels": [
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_request_duration_seconds_sum[15s]))/sum by (instance) (rate(http_request_duration_seconds_count[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_request_duration_seconds_count[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[15s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / $memory_limit",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes / v8_heap_size_limit",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client Errors (4xx)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{status=\"4xx\"} or http_request_duration_seconds_count * 0) by (instance) - sum(http_request_duration_seconds_count{status=\"4xx\"} offset $__interval or http_request_duration_seconds_count * 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Errors (5xx)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{status=\"5xx\"} or http_request_duration_seconds_count * 0) by (instance) - sum(http_request_duration_seconds_count{status=\"5xx\"} offset $__interval or http_request_duration_seconds_count * 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}